apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lego-server
  namespace: lego
spec:
  replicas: 1
  template:
    metadata:
      labels:
        # Required for the auto-create kube-lego-nginx service to work.
        app: kube-lego
        component: server
    spec:
      containers:
      - name: kube-lego
        image: jetstack/kube-lego:0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: LEGO_EMAIL
          valueFrom:
            configMapKeyRef:
              name: lego-config
              key: lego.email
        - name: LEGO_URL
          valueFrom:
            configMapKeyRef:
              name: lego-config
              key: lego.url
        - name: LEGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LEGO_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1